[package]
name = "task_remote"
version = "0.1.0"
authors = ["Werner Echezuria <werner_a_e@yahoo.es>"]

[dependencies]
gtk = "0.3.0"
gio = "0.3.0"
sourceview = "0.3.0"
webkit2gtk = "0.3.0"
diesel = { version = "1.1.1", features = ["sqlite"] }
dotenv = "0.9.0"
